name: Run Hello World

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run hello.py
        run: python hello.py
